# .github/actions/common-steps/action.yml

name: "Common Steps"
description: "Acciones comunes para configurar PHP, cache y dependencias"

inputs:
  php-version:
    description: "Versión de PHP a utilizar"
    required: true
    default: "8.4"

env:
  extensions: mbstring, intl, pdo_mysql
  key: cache-v1

runs:
  using: "composite"

  steps:
    - name: Setup cache environment
      id: extcache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ env.extensions }}
        key: ${{ env.key }}

    - name: Cache extensions
      uses: actions/cache@v3
      with:
        path: ${{ steps.extcache.outputs.dir }}
        key: ${{ steps.extcache.outputs.key }}
        restore-keys: |
          ${{ steps.extcache.outputs.key }}

    - name: Setup PHP ${{ inputs.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ env.extensions }}

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        key: composer-${{ hashFiles('**/composer.lock') }}-php-${{ inputs.php-version }}
        path: |
          ~/.composer/cache
          vendor
        restore-keys: |
          composer-${{ hashFiles('**/composer.lock') }}-php-${{ inputs.php-version }}
