name: Guru Man

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

envs_common: &envs_common
  extensions: mbstring, intl, pdo_mysql
  key: cache-v1

jobs:
  composer:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-version: [8.4]

    env:
      <<: *envs_common

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_mysql
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_mysql

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          key: composer-${{ hashFiles('**/composer.lock') }}-php-${{ matrix.php-version }}
          path: |
            ~/.composer/cache
            vendor
          restore-keys: composer-${{ hashFiles('**/composer.lock') }}-php-${{ matrix.php-version }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

  lint:
    runs-on: ubuntu-20.04
    needs: composer
    strategy:
      matrix:
        php-version: [8.4]

    env:
      extensions: mbstring, intl, pdo_mysql
      key: cache-v1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_mysql
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          key: composer-${{ hashFiles('**/composer.lock') }}-php-${{ matrix.php-version }}
          path: |
            ~/.composer/cache
            vendor
          restore-keys: composer-${{ hashFiles('**/composer.lock') }}-php-${{ matrix.php-version }}

      - name: Php lint
        run: composer lint-ci

  test:
    runs-on: ubuntu-20.04
    needs: composer
    strategy:
      matrix:
        php-version: [8.4]

    env:
      extensions: mbstring, intl, pdo_mysql
      key: cache-v1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_mysql
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          key: composer-${{ hashFiles('**/composer.lock') }}-php-${{ matrix.php-version }}
          path: |
            ~/.composer/cache
            vendor
          restore-keys: composer-${{ hashFiles('**/composer.lock') }}-php-${{ matrix.php-version }}

      - name: Php Pest
        run: composer test-ci
