name: Guru Man

on:
  push:
    branches:
      - main

jobs:
  avoid_reduncy:
    runs-on: ubuntu-20.04
    environment: cancel workflows, productions
    strategy:
      matrix:
        php-version: [8.4]

    steps:
      - name: token
        run: echo "${{ secrets.CANCEL_TOKEN }}....${{ secrets.GOGOG }}"

      - name: Cancel Previous Redundant Builds
        uses: action-pack/cancel@v1
        with:
          token: ${{ secrets.CANCEL_TOKEN }}
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: [8.4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Php Pest
        run: composer lint-ci

      - name: Php Pest
        run: composer test-ci
