name: Guru Man

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  extensions: mbstring, intl, pdo_mysql
  key: cache-v1

jobs:
  composer:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run common steps
        uses: ./.github/actions/common-steps/action.yml
        with:
          php-version: "8.4"

  lint:
    needs: composer
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run common steps
        uses: ./.github/actions/common-steps/action.yml
        with:
          php-version: "8.4"

      - name: Php lint
        run: composer lint-ci

  test:
    needs: composer
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run common steps
        uses: ./.github/actions/common-steps/action.yml
        with:
          php-version: "8.4"

      - name: Php Pest
        run: composer test-ci
