name: Guru Man

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  extensions: mbstring, intl, pdo_mysql
  key: cache-v1

jobs:
  composer:
    uses: ./.github/workflows/composersteps.yml
    with:
      php-version: "8.4"

  lint:
    uses: ./.github/workflows/composersteps.yml
    with:
      php-version: "8.4"
    needs: composer
    steps:
      - name: Php lint
        run: composer lint-ci

  test:
    uses: ./.github/workflows/composersteps.yml
    with:
      php-version: "8.4"
    needs: composer
    steps:
      - name: Php Pest
        run: composer test-ci
